name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine TAG_NAME
      id: tag_name
      run: |
        if [[ $GITHUB_REF == refs/heads/master ]]; then
          TAG_NAME=$(git describe --tags --abbrev=0)
        else
          TAG_NAME=$(git rev-parse --short HEAD)
        fi
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "::set-output name=TAG_NAME::$TAG_NAME"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yourdockerhubusername/yourrepository:${{ steps.tag_name.outputs.TAG_NAME }}
        build-args: |
          TAG_NAME=${{ steps.tag_name.outputs.TAG_NAME }}
